### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by surrealroad** [jpSimkins/Drupal2WordPress-Plugin#10]
Hi do you have a link to provide a donation for this excellent script?

**Comment by jpSimkins** [comment]
No donation link currently. I put this project online so others could use and grow the project. Leaving it as open-source allows this to become a more useful plugin that can grow with the community. I am working, slowly, on a new version of this plugin but I don't feel that donations would be appropriate due to my very limited time I can work on this project. Very much appreciate the offer for a donation but at this time, I don't see that as something I want to put here yet.
