### ISSUE TITLE
Content failed to import

### ISSUE THREAD

**Issue by rzach** [jpSimkins/Drupal2WordPress-Plugin#28]
Is there a way to figure out what's going wrong from this?

```
WordPress Tables Truncated - This ensures content/user IDs are synced across all systems
Error querying database. : SELECT DISTINCT n.nid AS id, n.uid AS post_author, FROM_UNIXTIME(n.created) AS post_date, r.body_value AS post_content, n.title AS post_title, r.body_summary AS post_excerpt, n.type AS post_type, IF(n.status = 1, 'publish', 'draft') AS post_status, a.alias FROM node n LEFT JOIN field_data_body r ON (r.entity_id = n.nid) LEFT JOIN url_alias a ON (REPLACE(a.source,'node/','') = n.nid) ORDER BY n.nid

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, null given in /homepages/4/d691843764/htdocs/clickandbuilds/Test/wp-content/plugins/drupal2wp/inc/Drupal2WordPress_DrupalDB.php on line 323

Content Failed to Import - All failed

Posted Type Updated

Comments Imported

Content Comments Count Updated
```

**Comment by jpSimkins** [comment]
That error is saying it had no results from the Drupal DB. At first, it seemed there was no Drupal DB connection but that doesn't seem the case.

Run the query manually on the Drupal DB to see if you get any other errors that could help identify the issue.

```
SELECT DISTINCT n.nid AS id, n.uid AS post_author, FROM_UNIXTIME(n.created) AS post_date, r.body_value AS post_content, n.title AS post_title, r.body_summary AS post_excerpt, n.type AS post_type, IF(n.status = 1, 'publish', 'draft') AS post_status, a.alias FROM node n LEFT JOIN field_data_body r ON (r.entity_id = n.nid) LEFT JOIN url_alias a ON (REPLACE(a.source,'node/','') = n.nid) ORDER BY n.nid
```

It's been a while since I've had time to work on this but I can try to help you as best I can.

**Comment by rzach** [comment]
It said:
`#1146 - Table 'db691844241.url_alias' doesn't exist `
I'm guessing it didn't import the sql dump properly/the dump wasn't complete. (It imported comments fine.)

**Comment by jpSimkins** [comment]
Hmm, first thing you need to check is to make sure that the table exists in the original dump. If not, I really couldn't say why that table is missing. It's needed to get the correct permalinks in place.

I would try to re-import the Drupal DB and run the script again. The comments most likely are not imported since there should be no content to attach to it. So it gives a false positive as it assumes no comments were needed.

**Comment by rzach** [comment]
If it shouldn't import comments if the content doesn't import then that's a bug since the comments are there. Thanks a million for the help! I'll report back!

**Comment by jpSimkins** [comment]
Yes and no. The comments were imported but you shouldn't have any content. Thus the comments should be pointless. A redundancy check could help that but then again, I don't want to assume anything with the importer. Although I too would consider this a bug.

Let me know if you resolve your issue.

**Comment by rzach** [comment]
Finally got a complete database dump and everything worked like a charm.
